### PR TITLE
Update dependencies (fix ws vulnerability)

### PR DESCRIPTION
**Pull request by dmitrizagidulin**

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
This is to address the 'npm audit' critical vuln in `ws` package.
cc @kjetilk / @RubenVerborgh

**Review by kjetilk — APPROVED** [review]
LGTM

**Comment by kjetilk** [comment]
Oh, too bad we hadn't merged this... But lets do now.

**Comment by kjetilk** [comment]
I looked over the deps and took the most recent versions, and put that into #16. I suppose that would supersede this, so closing.

**Pull request closed without merging**
