### PR TITLE
replace basename with dirname

### PR DESCRIPTION
**Pull request by melvincarvalho**

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
@melvincarvalho - thank you for the PR! Can you tell us a bit more about what it's trying to fix?

**Comment by melvincarvalho** [comment]
Consider the solid spec, when POSTing to an inbox.

Should something listening on the inbox be notified when a new resource is created?

From what I can tell.  The dirname command will notify the parent directory.  The basename will notify a string that is not a URI.

**Comment by dmitrizagidulin** [comment]
👍 , thanks @melvincarvalho! Merging.

**Comment by CxRes** [comment]
@melvincarvalho could you please explain the `if` statement in your change? AFAICT `parent` will never equal `req.originalUrl`?
```js
var parent = path.dirname(req.originalUrl) + path.sep
if (parent !== req.originalUrl) {
  solidWs.publish(parent)
}
```
 On the other hand you may want to check if you are at server root. Is that the intention?

**Comment by jaxoncreed** [comment]
NSS will also need a PR to update it's dependency on on this.

**Comment by CxRes** [comment]
@jaxoncreed May I suggest that you use dependabot on solid repos...

**Pull request merged**
